name: Cypress Tests CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use appropriate version

    - name: Install Dependencies
      run: |
        npm install --unsafe-perm=true

    - name: Ensure Cypress binary has proper permissions
      run: |
        sudo chmod -R 777 ./node_modules/.bin/cypress
        sudo chmod -R 777 ~/.cache/Cypress

    - name: Install Cypress binary
      run: |
        npx cypress install

    - name: Run Cypress Tests (UI & API)
      run: |
        npx cypress run --spec "cypress/e2e/uiTests/*.spec.js"
        npx cypress run --spec "cypress/e2e/apiTests/*.spec.js"

    - name: Upload Cypress Screenshots (if any)
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots/

    - name: Upload Cypress Videos (if any)
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos/

    # Caching Cypress binary to speed up the pipeline in future runs
    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-
