stages:
  - test

test:
  image: cypress/browsers:node16.14.0-chrome97-ff95  # Cypress Docker image with Chrome & Firefox
  stage: test
  script:
    - npm ci  # Install dependencies with a clean slate
    - npm start &  # Run the server in the background (if needed)
    - npx cypress run  # Run Cypress tests
  cache:
    paths:
      - node_modules/  # Cache node_modules to speed up future runs
      - ~/.cache/Cypress/  # Cache Cypress binary to avoid redownloading
