name: Cypress Tests CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use appropriate version

    - name: Install Dependencies
      run: |
        npm install --unsafe-perm=true

    - name: Clear npm cache (if necessary)
      run: |
        npm cache clean --force

    - name: Install Cypress binary
      run: |
        # Manually install Cypress without using npx
        npm install cypress --unsafe-perm=true

    - name: Set Cypress permissions
      run: |
        chmod -R 777 ./node_modules/.bin/cypress
        chmod -R 777 ~/.cache/Cypress

    - name: Run Cypress Tests (UI & API)
      run: |
        npx cypress run --spec "cypress/e2e/uiTests/*.spec.js"
        npx cypress run --spec "cypress/e2e/apiTests/*.spec.js"

    - name: Upload Cypress Screenshots (if any)
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: cypress/screenshots/

    - name: Upload Cypress Videos (if any)
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos/
