name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.5.0-chrome94-ff93
      options: --user 1001  # Ensure proper permissions for user

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          npm install --unsafe-perm=true

      - name: Install Cypress Binary (ensure proper permissions)
        run: |
          mkdir -p /home/runner/.cache/Cypress
          sudo chown -R $USER /home/runner/.cache/Cypress
          npx cypress install --unsafe-perm=true

      - name: Run Cypress Tests (UI & API)
        run: |
          npx cypress run --spec "cypress/e2e/uiTests/*.spec.js"
          npx cypress run --spec "cypress/e2e/apiTests/*.spec.js"
